### ISSUE TITLE
Cuda Version of the drivers shows multiple bugs on Orin AGX

### ISSUE THREAD

**Issue by MatteGombia** [HesaiTechnology/HesaiLidar_ROS_2.0#37]
I'm on Orin AGX, OS: jetsonpack6, Driver Version: 540.4.0, CUDA Version: 12.6, Lidar: OT128
I'm facing multiple bugs, which in the version without cuda don't appear.

1: Imu values are not published at all
2: the parameters fov_start, fov_end don't have any effect and they don't change the fov range

I also tried to change the line as internet suggested me, but nothing changed
```
set(CUDA_NVCC_FLAGS "-arch=sm_87;-O2")#根据具体GPU性能更改算力参数
```

![Image](https://github.com/user-attachments/assets/2583acec-19d7-4631-9361-74d623dbae35)

config: 
```
lidar:
  - driver:
      pcap_play_synchronization: false  # pcap play rate synchronize with the host time
      udp_port: 2368                   #UDP port of lidar
      ptc_port: 9347                   #PTC port of lidar
      device_ip_address: 192.168.1.201 #host_ip_address
      group_address: 255.255.255.0
      pcap_path: "" #"/home/orin/Downloads/pcap/fisso_pitch_8"      #The path of pcap file
      correction_file_path: "/home/orin/ros2_ws/src/HesaiLidar_ROS_2.0/src/driver/HesaiLidar_SDK_2.0/correction/angle_correction/OT128_Angle Correction File.csv" #The path of correction file
      firetimes_path: "/home/orin/ros2_ws/src/HesaiLidar_ROS_2.0/src/driver/HesaiLidar_SDK_2.0/correction/firetime_correction/OT128_Firetime Correction File.csv"         #The path of firetimes file
      source_type: 1                                 #The type of data source, 1: real-time lidar connection, 2: pcap, 3: packet rosbag, 4: serial    
      frame_start_azimuth: -1         #Frame azimuth for Pandar128, range from 1 to 359, set it less than 0 if you do not want to use it
      standby_mode: -1                 #The standby mode: [-1] is invalit [0] in operation [1] standby
      speed: 600                          #The speed: [-1] invalit, you must make sure your set has been supported by the lidar you are using
      #lidar configuration using serial communication
      rs485_com: "Your serial port name for receiving point cloud"  # if using JT16, Port to receive the point cloud
      rs232_com: "Your serial port name for sending cmd"            # if using JT16, Port to send cmd
      correction_save_path: ""         # if using JT16, turn on when you need to store angle calibration files(from lidar)
      #transform param
      x: 0
      y: 0
      z: 1.05
      roll: 0.15
      pitch: -0.025   
      yaw: 0
      #decoder param
      use_timestamp_type: 0           #0 use point cloud timestamp; 1 use receive timestamp
      #fov config, [fov_start, fov_end] range [1, 359], [-1, -1]means use default
      fov_start: 90
      fov_end: 270
      enable_packet_loss_tool: true     # enable the udp packet loss detection tool
      distance_correction_lidar_flag: false # set to true when optical centre correction needs to be turned on
      xt_spot_correction: false             # Set to TRUE when XT S point cloud layering correction is required
      device_udp_src_port: 0                # Filter point clouds for specified source ports in case of multiple lidar, setting >=1024
      device_fault_port: 0                  # Filter fault message for specified source ports in case of multiple lidar, setting >=1024
    ros:
      ros_frame_id: hesai_lidar                     #Frame id of packet message and point cloud message
      # ros_recv_correction_topic: /lidar_corrections #Topic used to receive corrections file from rosbag
      ros_recv_packet_topic: /lidar_packets         #Topic used to receive lidar packets from rosbag
      ros_send_packet_topic: /lidar_packets         #Topic used to send lidar raw packets through ROS
      ros_send_point_cloud_topic: /lidar_points     #Topic used to send point cloud through ROS
      # ros_send_correction_topic: /lidar_corrections #Topic used to send correction through ROS
      # ros_send_firetime_topic: /lidar_firetime
      ros_send_packet_loss_topic: /lidar_packets_loss
      ros_send_imu_topic: /lidar_imu                #Topic used to send lidar imu message
      # Topic used to monitor packets loss condition through ROS
      # ros_send_ptp_topic: /lidar_ptp
      # Topic used to send PTP lock status, offset through ROS
      send_packet_ros: true                         #true: Send packets through ROS 
      send_point_cloud_ros: true                    #true: Send point cloud through ROS    
```
