### ISSUE TITLE
The Hesai JT16 point cloud is not displaying in RViz.

### ISSUE THREAD

**Issue by marcinmatecki** [HesaiTechnology/HesaiLidar_ROS_2.0#52]
Hi,
I have a problem: the JT16 is connected via RS485 and is working in PandarView 2, but nothing is displayed in RViz. Below is my config.yaml file.

lidar:
  - driver:
      pcap_play_synchronization: true  # pcap play rate synchronize with the host time
      udp_port: 2368                   #UDP port of lidar
      ptc_port: 9347                   #PTC port of lidar
      device_ip_address: 192.168.1.201 #host_ip_address
      group_address: 255.255.255.255
      pcap_path: "Your pcap file"      #The path of pcap file
      correction_file_path: "Your correction file path" #The path of correction file
      firetimes_path: "Your firetime file path"         #The path of firetimes file
      source_type: 4                              #The type of data source, 1: real-time lidar connection, 2: pcap, 3: packet rosbag, 4: serial    
      frame_start_azimuth: 0         #Frame azimuth for Pandar128, range from 1 to 359, set it less than 0 if you do not want to use it
      standby_mode: -1                 #The standby mode: [-1] is invalit [0] in operation [1] standby
      speed: -1                        #The speed: [-1] invalit, you must make sure your set has been supported by the lidar you are using
      #lidar configuration using serial communication
      rs485_com: "/dev/ttyUSB0"  # if using JT16, Port to receive the point cloud
      rs232_com: ""            # if using JT16, Port to send cmd
      correction_save_path: ""         # if using JT16, turn on when you need to store angle calibration files(from lidar)
      #transform param
      x: 0
      y: 0
      z: 0
      roll: 0
      pitch: 0
      yaw: 0
      #decoder param
      use_timestamp_type: 0           #0 use point cloud timestamp; 1 use receive timestamp
      #fov config, [fov_start, fov_end] range [1, 359], [-1, -1]means use default
      fov_start: -1
      fov_end:  -1
      enable_packet_loss_tool: true     # enable the udp packet loss detection tool
      distance_correction_lidar_flag: false # set to true when optical centre correction needs to be turned on
      xt_spot_correction: false             # Set to TRUE when XT S point cloud layering correction is required
      device_udp_src_port: 0                # Filter point clouds for specified source ports in case of multiple lidar, setting >=1024
      device_fault_port: 0                  # Filter fault message for specified source ports in case of multiple lidar, setting >=1024
    ros:
      ros_frame_id: hesai_lidar                     #Frame id of packet message and point cloud message
      #ros_recv_correction_topic: /lidar_corrections #Topic used to receive corrections file from rosbag
      ros_recv_packet_topic: /lidar_packets         #Topic used to receive lidar packets from rosbag
      ros_send_packet_topic: /lidar_packets         #Topic used to send lidar raw packets through ROS
      ros_send_point_cloud_topic: /lidar_points     #Topic used to send point cloud through ROS
      #ros_send_correction_topic: /lidar_corrections #Topic used to send correction through ROS
      #ros_send_firetime_topic: /lidar_firetime
      ros_send_packet_loss_topic: /lidar_packets_loss
      ros_send_imu_topic: /lidar_imu                #Topic used to send lidar imu message
      #Topic used to monitor packets loss condition through ROS
      #ros_send_ptp_topic: /lidar_ptp
      #Topic used to send PTP lock status, offset through ROS
      send_packet_ros: true                         #true: Send packets through ROS 
      send_point_cloud_ros: true                    #true: Send point cloud through ROS    

![Image](https://github.com/user-attachments/assets/37bfb8c8-8a43-44ab-9be4-3ee0f308e0aa)
![Image](https://github.com/user-attachments/assets/0e15cfb4-21a0-4933-927e-06131e7817a3)

I am using the following operating system:

PRETTY_NAME="Ubuntu 22.04.5 LTS"
NAME="Ubuntu"
VERSION_ID="22.04"
VERSION="22.04.5 LTS (Jammy Jellyfish)"

I would appreciate any help or suggestions. Thank you in advance.

**Comment by changxingshuo** [comment]
Looking at your configuration file and realizing that you have not configured the rs232_com port, you cannot get the angle correction file from within the radar. Therefore you need to additionally configure the correction_file_path path to specify the use of a local angle calibration file.

**Comment by suke-toudara** [comment]
I configured the yaml file and selected the rs232 port, but it did not work.
Similarly, it is visible from the viewer.

```
lidar:
  - driver:
      pcap_play_synchronization: true  # pcap play rate synchronize with the host time
      udp_port: 2368                   #UDP port of lidar
      ptc_port: 9347                   #PTC port of lidar
      device_ip_address: 192.168.1.201 #host_ip_address
      group_address: 255.255.255.255
      pcap_path: "Your pcap file"      #The path of pcap file
      correction_file_path: "" #The path of correction file
      firetimes_path: "Your firetime file path"         #The path of firetimes file
      source_type: 4                                 #The type of data source, 1: real-time lidar connection, 2: pcap, 3: packet rosbag, 4: serial    
      frame_start_azimuth: 0         #Frame azimuth for Pandar128, range from 1 to 359, set it less than 0 if you do not want to use it
      standby_mode: -1                 #The standby mode: [-1] is invalit [0] in operation [1] standby
      speed: -1                        #The speed: [-1] invalit, you must make sure your set has been supported by the lidar you are using
      #lidar configuration using serial communication
      rs485_com: "/dev/ttyUSB2"  # if using JT16, Port to receive the point cloud
      rs232_com: "/dev/ttyUSB0"            # if using JT16, Port to send cmd
      correction_save_path: ""         # if using JT16, turn on when you need to store angle calibration files(from lidar)
      #transform param
      x: 0
      y: 0
      z: 0
      roll: 0
      pitch: 0
      yaw: 0
      #decoder param
      use_timestamp_type: 0           #0 use point cloud timestamp; 1 use receive timestamp
      #fov config, [fov_start, fov_end] range [1, 359], [-1, -1]means use default
      fov_start: -1
      fov_end:  -1
      enable_packet_loss_tool: true     # enable the udp packet loss detection tool
      distance_correction_lidar_flag: false # set to true when optical centre correction needs to be turned on
      xt_spot_correction: false             # Set to TRUE when XT S point cloud layering correction is required
      device_udp_src_port: 0                # Filter point clouds for specified source ports in case of multiple lidar, setting >=1024
      device_fault_port: 0                  # Filter fault message for specified source ports in case of multiple lidar, setting >=1024
    ros:
      ros_frame_id: hesai_lidar                     #Frame id of packet message and point cloud message
      # ros_recv_correction_topic: /lidar_corrections #Topic used to receive corrections file from rosbag
      ros_recv_packet_topic: /lidar_packets         #Topic used to receive lidar packets from rosbag
      ros_send_packet_topic: /lidar_packets         #Topic used to send lidar raw packets through ROS
      ros_send_point_cloud_topic: /lidar_points     #Topic used to send point cloud through ROS
      # ros_send_correction_topic: /lidar_corrections #Topic used to send correction through ROS
      # ros_send_firetime_topic: /lidar_firetime
      ros_send_packet_loss_topic: /lidar_packets_loss
      ros_send_imu_topic: /lidar_imu                #Topic used to send lidar imu message
      # Topic used to monitor packets loss condition through ROS
      # ros_send_ptp_topic: /lidar_ptp
      # Topic used to send PTP lock status, offset through ROS
      send_packet_ros: true                         #true: Send packets through ROS 
      send_point_cloud_ros: true                    #true: Send point cloud through ROS    

```
